### ISSUE TITLE
Option to specify/shorten video duration

### ISSUE THREAD

**Issue by TheLastGimbus** [opsxcq/meme-vibing-cat#2]
Just like @relishcolouredhat said, we need to shitpost **faster** :smirk_cat: 

Please add option to set duration to only 15 secods or something. Right now, the output has 30mb :flushed: 

Also, option to pass extra parameters to ffmpeg would be nice, but that's not necessary. Or more options: to make output `.webp`, etc

Thanks :heart_eyes_cat:

**Comment by ohmydevops** [comment]
it's done #4 @opsxcq @TheLastGimbus

**Comment by TheLastGimbus** [comment]
Nice 😸

Add "fixes #2" in the description, so this issue will automatically close when it's merged

If you could also add `.webm`/custom format option, I would be really grateful

**Comment by ohmydevops** [comment]
- Thanks for the point.
- I will add that feature on the weekend as well ( I mean Iranian weekends :) )
